import Head from "next/head";
import Hero from "../components/Hero";
import Nav from "../components/Nav";
import Boxed from "../components/Boxed";
import Footer from "../components/Footer";
import { Box } from "@chakra-ui/react";
import SimpleThreeColumns from "../components/Features";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div>
				<Nav />
				<Hero />
				<Boxed />
				<Footer />
			</div> */}
      <Box
        w="full"
        h="600px"
        px={"130px"}
        backgroundImage="url('/hue.png')"
        backgroundPosition="center top"
        backgroundRepeat="no-repeat"
        backgroundSize="cover"
      >
        <Nav />
        <Hero />
      </Box>{" "}
      <SimpleThreeColumns />
      <Footer />
    </div>
  );
}
