import React from 'react';
import Head from 'next/head';
function Home() {
	return (
		<div className="style">
			<Head>
				<title>Home App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>
				<center>Nwalo</center>
			</h1>
		</div>
	);
}

export default Home;
